[project]
name = "stx-microloan-smart-contract"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/stx-microloan-smart-contract/stx-microloan-smart-contract/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.stx-microloan-smart-contract]
path = "contracts/stx-microloan-smart-contract.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
